### ISSUE TITLE
internal/external lb setting

### ISSUE THREAD

**Issue by ccollicutt** [OpenStackSanDiego/osa-workshop#1]
I think these need to be set.

```
TASK [Backup the default pip_install_upper_constraints] **************************************************************************************************************************************
fatal: [control-00]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'internal_lb_vip_address' is undefined\n\nThe error appears to have been in '/opt/openstack-ansible/playbooks/common-tasks/set-pip-vars.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Backup the default pip_install_upper_constraints\n  ^ here\n"}
```

eg.

```
global_overrides:
  cidr_networks: *cidr_networks
  #
  # The below domain name must resolve to an IP address
  # in the CIDR specified in haproxy_keepalived_external_vip_cidr.
  # If using different protocols (https/http) for the public/internal
  # endpoints the two addresses must be different.
  #
  tunnel_bridge: "br-mgmt"
  management_bridge: "br-mgmt"
  internal_lb_vip_address: 10.99.181.131
  external_lb_vip_address: 147.75.96.2
SNIP!
```
