### ISSUE TITLE
setup br-vxlan

### ISSUE THREAD

**Issue by ccollicutt** [OpenStackSanDiego/osa-workshop#10]
According to the [docs](https://docs.openstack.org/project-deploy-guide/openstack-ansible/newton/overview-network-arch.html) we'll need a `br-vxlan` interface. I'm assuming this must exist on compute and control, as control will act as a network node.

```
The br-vxlan bridge is required if the environment is configured to allow projects to create virtual networks. It provides the interface for virtual (VXLAN) tunnel networks.

The bridge attaches to a physical or logical interface, typically a bond1 VLAN subinterface. It also attaches to eth10 in each associated container.

The container network interface it attaches to is configurable in the openstack_user_config.yml file.
```

**Comment by ccollicutt** [comment]
I manually setup br-vxlan on both nodes using the vxlan networks that are created by the current tf code.

Then I setup the deploy yaml to do:

```
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
```
But when validating am missing vxlan/tunnel cidr.
```
root@infra0:/opt/openstack-ansible/playbooks# openstack-ansible -vvvv setup-infrastructure.yml --syntax-check
Variable files: "-e @/etc/openstack_deploy/user_secrets.yml -e @/etc/openstack_deploy/user_variables.yml "
ansible-playbook 2.5.10
  config file = None
  configured module search path = [u'/etc/ansible/roles/plugins/library', u'/etc/ansible/roles/ceph-ansible/library']
  ansible python module location = /opt/ansible-runtime/local/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible-runtime/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
No config file found; using defaults
setting up inventory plugins
 [WARNING]:  * Failed to parse /opt/openstack-ansible/inventory/dynamic_inventory.py with script plugin: Inventory script (/opt/openstack-ansible/inventory/dynamic_inventory.py) had an
execution error: can't find tunnel in cidr_networks
```
